### ISSUE TITLE
Add support for getting all devices 

### ISSUE THREAD

**Issue by guyluz11** [ianmaciel/dart_ewelink_api#11]
I would like to implement this package in my open-source smart home system [CyBear Jinni](https://github.com/CyBear-Jinni), but it will be drastically better and more convenient if I am able to show the user all of his devices without his need to search where to get the id in the app and add all of the ids one by one. 
 
https://github.com/ianmaciel/dart_ewelink_api/blob/b5d945ae7c4b7ee8304e34a93462f63b07e17101/example/main.dart#L39

**Comment by guyluz11** [comment]
Probably in the future, currently working on adding xiaomi device support with the help of another package.

**Comment by guyluz11** [comment]
Found where the npm package that we are based on is doing the call to get all devices

Doc: https://github.com/skydiver/ewelink-api/blob/master/docs/available-methods/getdevices.md

Call in code: https://github.com/skydiver/ewelink-api/blob/master/src/mixins/getDevices.js

**Comment by ianmaciel** [comment]
Contradicting myself I have just created the method to get all devices.
https://github.com/ianmaciel/dart_ewelink_api/pull/15

**Comment by guyluz11** [comment]
That's so cool of you, thanks.

Will start implementing this package into cbj sooner than expected  😆

**Comment by ianmaciel** [comment]
Would you like to review?

**Comment by guyluz11** [comment]
Done
