### ISSUE TITLE
Erro na rotina ewelink_user.g.dart

### ISSUE THREAD

**Issue by samic2020** [ianmaciel/dart_ewelink_api#6]
Boa noite.
Estou tentando rodar o exemplo e esta dando erro no modulo ewelink_user.g.dart linha 15 na instrução json['bindInfos'], Ela responde que esta retornando null.

EwelinkUser _$EwelinkUserFromJson(Map<String, dynamic> json) => EwelinkUser(
      json['apikey'] as String,
      json['appId'] as String,
      (json['appInfos'] as List<dynamic>)
          .map((e) => EwelinkAppInfos.fromJson(e as Map<String, dynamic>))
          .toList(),
      **json['bindInfos'] as Map<String, dynamic>,** Esta dando erro nesta linha quando executo o exemplo.

**Comment by ianmaciel** [comment]
Qual erro aconteceu? Na hora da execução ou na hora de compilar?

E qual versão do Flutter você está usando?

**Comment by samic2020** [comment]
Estou usando a penultima versão do flutter.
O erro esta na execução.
Quando ele vai no json['bindInfos'], não existe mais bindInfos no json.

**Comment by ianmaciel** [comment]
Tente usar a versão mais antiga, a versão da época que foi feita: (3.0.5)[https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.0.5-stable.zip]

**Comment by ianmaciel** [comment]
Você quis dizer que o `bindInfos` nao existe no seu usuário?
Você pode adicionar o json que você recebe da requisição no watch e colar ele aqui para eu ver?

por exemplo eu recebi isso:

```
"clientInfo" -> Map (5 items)
"_id" -> "---"
"email" -> "----"
"password" -> "----"
"appId" -> "----"
"isAccepEmailAd" -> false
"createdAt" -> "2019-09-17T22:18:31.036Z"
"apikey" -> "----"
"__v" -> 0
"lang" -> "us"
"online" -> false
"onlineTime" -> "2023-01-05T18:20:58.058Z"
"appInfos" -> List (1 item)
"ip" -> "----"
"location" -> ""
"offlineTime" -> "2023-01-05T18:23:38.275Z"
"userStatus" -> "2"
"bindInfos" -> Map (1 item)
"countryCode" -> "+1"
"currentFamilyId" -> "----"
"language" -> "pt-BR"
"extraPush" -> Map (1 item)
"extra" -> Map (1 item)
"accountInfo" -> Map (3 items)
"platformLang" -> Map (1 item)
```

Obs. cuidado para não publicar dados sensíveis.

**Comment by ianmaciel** [comment]
Por falta de movimentação, vou fechar a issue. É provável que ela não exista mais com a versão mais nova.
